version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=goauthbackend_dev
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: always
    
